### ISSUE TITLE
Can't use URLs behind a subpath

### ISSUE THREAD

**Issue by nettosama** [home-assistant-ecosystem/python-netdata#1]
The standard format to access netdata in this module is:

'http://{host}:{port}/api/v{api}/'

But there are some cases in which the Netdata URL could be like this:

'http://{host}:{port}/{path}/api/v{api}/'

Please add an option as a optional parameter to format it like this

**Comment by ghartong** [comment]
Facing same problem. Freenas 11 sets up NetData as a service available at http://{host}/netdata so the api is at http://{host}/netdata/api/v{api}. The addition of a {path} parameter would be great.
