### ISSUE TITLE
Be more explicit with API endpoint

### ISSUE THREAD

**Issue by jurgenhaas** [home-assistant-ecosystem/python-netdata#3]
Currently, when the Netdata object gets instantiated, the endpoint gets determined as either `_ALL_METRIC_ENDPOINT` or `_ALARMS_ENDPOINT` or `_DATA_ENDPOINT` which causes an issue when you use this package to integrate for multi-purpose environments.

I'm currently working on the improvement of the Home-Assistant integration (home-assistant/core/pull/34339) and there we collect both metric data and alarms but want to deal with one Netdata instance for each host only.

It would be very helpful if you could change the 3 functions in the Netdata class such that they always defined their required endpoint, i.e.

- get_allmetrics() should call `self.endpoint = _ALL_METRIC_ENDPOINT`
- get_alarms() should call `self.endpoint = _ALARMS_ENDPOINT`
- get_data() should call `self.endpoint = _DATA_ENDPOINT`

If you accepted this proposal, I'm happy to provide a PR.

**Comment by fabaff** [comment]
> Currently, when the Netdata object gets instantiated, the endpoint gets determined as either _ALL_METRIC_ENDPOINT or _ALARMS_ENDPOINT or _DATA_ENDPOINT which causes an issue when you use this package to integrate for multi-purpose environments.

As far as I remember was that a compromise when I added the new endpoint to keep it working with the Home Assistant integration.

Yes, please create a PR. Looks like that it doesn't harm if `data` is removed.
